### ISSUE TITLE
执行报错：TypeError: load_model() got an unexpected keyword argument 'vad_model_fp'

### ISSUE THREAD

**Issue by zxy719** [nkilm/offline-whisperx#1]
脚本无法运行，参数是按照testing.py里面提供的原始内容进行填写的

**Comment by nkilm** [comment]
请问您能否提供可以重现此问题的代码？

**Comment by zmwv823** [comment]
> 请问您能否提供可以重现此问题的代码？
```
from .offline_whisperx.transcriber import Transcriber, TranscriptionConfig
            FASTER_WHISPER_PATH = model_path
            ALIGN_MODEL_DIR = r"C:\Users\pc\Desktop\models--facebook--wav2vec2-base-960h"
            VAD_MODEL_FP = r"C:\Users\pc\.cache\torch\whisperx-vad-segmentation.bin"
            
            PYANNOTE_CONFIG_PATH = os.path.join(current_directory, 'offline_whisperx\pyannote_config.yaml')
            temp_srt_dir = os.path.join(sys_temp_dir, f'{srt_name}.srt')
            # change the config as per your requirements
            config = TranscriptionConfig(
                whisper_model_name=FASTER_WHISPER_PATH,  # provide whisper model name or path
                align_model_dir=ALIGN_MODEL_DIR,
                vad_model_fp=VAD_MODEL_FP,
                pyannote_config_path=PYANNOTE_CONFIG_PATH,
                compute_type=faster_whisper_dtype,
                diarize=True,
                output_dir=temp_srt_dir,
                output_format="srt",
            )
            audio_file = audio_save_path
            transcriber = Transcriber(config)
            transcriptions = transcriber.transcribe(audio_path=audio_file)
            transcriptions = transcriber.align_transcriptions(transcriptions)
            transcriptions = transcriber.diarize_transcriptions(transcriptions)
            transcriber.write_transcriptions(transcriptions=transcriptions)
```

```
!!! Exception during processing!!! load_model() got an unexpected keyword argument 'vad_model_fp'
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-UL\DataProcess\nodes.py", line 504, in UL_DataProcess_Faster_Whisper
    transcriptions = transcriber.transcribe(audio_path=audio_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-UL\DataProcess\offline_whisperx\transcriber.py", line 176, in transcribe
    model = self.load_asr_model()
            ^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-UL\DataProcess\offline_whisperx\transcriber.py", line 137, in load_asr_model
    return load_model(
           ^^^^^^^^^^^
TypeError: load_model() got an unexpected keyword argument 'vad_model_fp'

Prompt executed in 9.12 seconds
```

**Comment by zmwv823** [comment]
> 请问您能否提供可以重现此问题的代码？

这个很好解决（改个参数），后面一大串才难搞（hotwords=None、音频加载出错(成str类型了)、当srt文件已存在时，无法创建该文件）。
可能是whipser版本问题吧。

**Comment by rayblade** [comment]
您好，我也遇到了同样的报错信息，具体如下：
Traceback (most recent call last):
  File "D:\whisperxoffline\testing.py", line 28, in <module>
    transcriptions = transcriber.transcribe(audio_path=audio_file)
  File "D:\whisperxoffline\transcriber.py", line 176, in transcribe
    model = self.load_asr_model()
  File "D:\whisperxoffline\transcriber.py", line 137, in load_asr_model
    return load_model(
TypeError: load_model() got an unexpected keyword argument 'vad_model_fp'

testing.py里的内容几乎没有改动，相关代码如下：
MODELS_DIR = r"./models"

FASTER_WHISPER_PATH = f"{MODELS_DIR}/faster_whisper_base"
ALIGN_MODEL_DIR = f"{MODELS_DIR}/wav2vec2_base"
VAD_MODEL_FP = f"{MODELS_DIR}/voice_activity_detection/whisperx_vad_segmentation.bin"

PYANNOTE_CONFIG_PATH = "./pyannote_config.yaml"

model是按照testing.py、pyannote_config.yaml和您之前回答里的截图所存放。
测试了把testing.py和transcriber.py编码修改为UTF-8，问题依旧。
检查了load_asr_model函数里的self.config.vad_model_fp类型为str
请帮忙看看是我哪里弄错了呢？
