### ISSUE TITLE
还是会去抱脸下载模型

### ISSUE THREAD

**Issue by xiexidong** [nkilm/offline-whisperx#6]
执行了pip install -r requirements.txt
将所有模型都本地化了
![image](https://github.com/user-attachments/assets/0eb4ce75-7f2f-4589-a718-31dffc7c1270)
执行python testing.py 报错
(whisperx-offline) jzxt@jzxt-SY-KL-H510M-F:~/soft/123/offline-whisperx-main/offline-whisperx-main$ python testing.py 
INFO:speechbrain.utils.quirks:Applied quirks (see `speechbrain.utils.quirks`): [allow_tf32, disable_jit_profiling]
INFO:speechbrain.utils.quirks:Excluded quirks specified by the `SB_DISABLE_QUIRKS` environment (comma-separated list): []
/home/jzxt/anaconda3/envs/whisperx-offline/lib/python3.10/site-packages/pyannote/audio/pipelines/speaker_verification.py:45: UserWarning: Module 'speechbrain.pretrained' was deprecated, redirecting to 'speechbrain.inference'. Please update your script. This is a change from SpeechBrain 1.0. See: https://github.com/speechbrain/speechbrain/releases/tag/v1.0.0
  from speechbrain.pretrained import (
Traceback (most recent call last):
  File "/home/jzxt/soft/123/offline-whisperx-main/offline-whisperx-main/testing.py", line 27, in <module>
    transcriptions = transcriber.transcribe(audio_path=audio_file)
  File "/home/jzxt/soft/123/offline-whisperx-main/offline-whisperx-main/transcriber.py", line 176, in transcribe
    model = self.load_asr_model()
  File "/home/jzxt/soft/123/offline-whisperx-main/offline-whisperx-main/transcriber.py", line 137, in load_asr_model
    return load_model(
  File "/home/jzxt/anaconda3/envs/whisperx-offline/lib/python3.10/site-packages/whisperx/asr.py", line 289, in load_model
    model = model or WhisperModel(whisper_arch,
  File "/home/jzxt/anaconda3/envs/whisperx-offline/lib/python3.10/site-packages/faster_whisper/transcribe.py", line 127, in __init__
    model_path = download_model(
  File "/home/jzxt/anaconda3/envs/whisperx-offline/lib/python3.10/site-packages/faster_whisper/utils.py", line 103, in download_model
    return huggingface_hub.snapshot_download(repo_id, **kwargs)
  File "/home/jzxt/anaconda3/envs/whisperx-offline/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/jzxt/anaconda3/envs/whisperx-offline/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/jzxt/soft/123/models/faster_whisper_base'. Use `repo_type` argument if needed.

配置文件为
from transcriber import Transcriber, TranscriptionConfig

# all required models are available in the models directory
MODELS_DIR = r"/home/jzxt/soft/123/models"

FASTER_WHISPER_PATH = f"{MODELS_DIR}/faster_whisper_base"
ALIGN_MODEL_DIR = f"{MODELS_DIR}/wav2vec2_base"
VAD_MODEL_FP = f"{MODELS_DIR}/voice_activity_detection/pytorch_model.bin"

PYANNOTE_CONFIG_PATH = "./pyannote_config.yaml"

# change the config as per your requirements

  name: pyannote.audio.pipelines.SpeakerDiarization
  params:
    clustering: AgglomerativeClustering
    embedding: /home/jzxt/soft/123/models/wespeaker-voxceleb-resnet34-LM/pytorch_model.bin
    embedding_batch_size: 32
    embedding_exclude_overlap: true
    segmentation: /home/jzxt/soft/123/models/segmentation-3.0/pytorch_model.bin
    segmentation_batch_size: 32
    
    我是遗漏掉了什么步骤吗？感谢您的回复

**Comment by xiexidong** [comment]
我已经按照您的图示，将我的目录结构改为和您一致，并且配置文件也和您的一样，但是这个错误依旧存在
期盼您的指导
![image](https://github.com/user-attachments/assets/af6f4674-4a0b-4add-b264-add1b59e89ab)

**Comment by nkilm** [comment]
Hi @xiexidong, 

Thank you for reaching out. I remember getting this exact error, it is because the script is not able to locate the model. For your reference, I've attached the screenshot of the folder structure which is working in my case. 

![image](https://github.com/user-attachments/assets/59f6f0f3-244c-49bf-93cb-b01f9a662c0d)

Also check `~/.cache/huggingface/hub` if it's trying to load something from there? Try clearing your huggingface cache folder and try executing the script again. Additionally, check if you are using correct version of packages/libraries mentioned in [requirements.txt](https://github.com/nkilm/offline-whisperx/blob/main/requirements.txt).

I hope this helps.
Regards,
@nkilm

**Comment by xiexidong** [comment]
Sincerely grateful for your reply. I will continue to test this feature and synchronize my results with you.
Thanks again @nkilm
